apiVersion: v1
kind: Secret
metadata:
  name: university-secrets
  namespace: university
type: Opaque
stringData:
  # SQL Server password
  SA_PASSWORD: "My!P@ssword1"
  # Connection strings
  SQLSERVER_CONNECTION: "Server=sqldata;Database=ContosoUniversity1;User Id=sa;Password=My!P@ssword1;TrustServerCertificate=True"
  COURSES_DB_CONNECTION: "Server=sqldata;Database=ContosoUniversity1;User Id=sa;Password=My!P@ssword1;TrustServerCertificate=True"
  # RabbitMQ
  RABBITMQ_HOST: "amqp://guest:guest@rabbitmq:5672"
